#!/bin/bash

# 颜色定义
info() {
  tput setaf 3  
  echo "[INFO] $1"
  tput sgr0
}

error() {
  tput setaf 1
  echo "[ERROR] $1"
  tput sgr0
  exit 1
}

# パラメータ設定
ENABLE_KPM=false # KPMを無効に設定
ENABLE_LZ4KD=true

# 機種選択
info "请选择要编译的机型："
info "1. 一加 Ace 5 Pro"
info "2. 一加 13"
info "3.一加 13T"
info "4.一加 Pad 2 Pro"
info "5.一加 Ace5 至尊版"
info "6.真我 GT 7 Pro"
info "7.真我 GT 7 Pro 竞速版"

# デバイスをRealme GT7 Proに固定
device_choice=6 # Realme GT7 Proに固定

case $device_choice in
    1)
        DEVICE_NAME="oneplus_ace5_pro"
        REPO_MANIFEST="JiuGeFaCai_oneplus_ace5_pro_v.xml"
        KERNEL_TIME="Tue Dec 17 23:36:49 UTC 2024"
        KERNEL_SUFFIX="-android15-8-g013ec21bba94-abogki383916444-4k"
        ;;
    2)
        DEVICE_NAME="oneplus_13"
        REPO_MANIFEST="JiuGeFaCai_oneplus_13_v.xml"
        KERNEL_TIME="Tue Dec 17 23:36:49 UTC 2024"
        KERNEL_SUFFIX="-android15-8-g013ec21bba94-abogki383916444-4k"
        ;;
    3)
        DEVICE_NAME="oneplus_13t"
        REPO_MANIFEST="oneplus_13t.xml"
        KERNEL_TIME="FriApr 25 01:56:53 UTC 2025"
        KERNEL_SUFFIX="-android15-8-gba3bcfd39307-abogki413159095-4k"
        ;;
    4)
        DEVICE_NAME="oneplus_pad_2_pro"
        REPO_MANIFEST="oneplus_pad_2_pro.xml"
        KERNEL_TIME="Wed Dec 11 19:16:38 UTC 2024"
        KERNEL_SUFFIX="-android15-8-g0261dbe3cf7e-ab12786384-4k"
        ;;
    5)
        DEVICE_NAME="oneplus_ace5_ultra"
        REPO_MANIFEST="oneplus_ace5_ultra.xml"
        KERNEL_TIME="Fri Apr 18 19:35:07 UTC 2025"
        KERNEL_SUFFIX="-android15-8-gfc70d29746a7-abogki412262948-4k"
        ;;
    6)
        [span_0](start_span)DEVICE_NAME="realme_GT7pro"[span_0](end_span)
        [span_1](start_span)REPO_MANIFEST="realme_GT7pro.xml"[span_1](end_span)
        [span_2](start_span)KERNEL_TIME="Tue Dec 17 23:36:49 UTC 2024"[span_2](end_span)
        [span_3](start_span)KERNEL_SUFFIX="-android15-8-g013ec21bba94-abogki383916444-4k"[span_3](end_span)
        ;;
    7)
        [span_4](start_span)DEVICE_NAME="realme_GT7pro_Speed"[span_4](end_span)
        [span_5](start_span)REPO_MANIFEST="realme_GT7pro_Speed.xml"[span_5](end_span)
        [span_6](start_span)KERNEL_TIME="Tue Dec 17 23:36:49 UTC 2024"[span_6](end_span)
        [span_7](start_span)KERNEL_SUFFIX="-android15-8-g013ec21bba94-abogki383916444-4k"[span_7](end_span)
        ;;
    *)
        [span_8](start_span)error "无效的选择，请输入1-3之间的数字"[span_8](end_span)
        ;;
esac

# カスタムパッチ
# 関数：入力判断用、無効な入力はデフォルト値を返すことを保証
prompt_boolean() {
    local prompt="$1"
    local default_value="$2"
    local result
    read -p "$prompt" result
    case "$result" in
        [nN]) echo false ;;
        [span_9](start_span)[yY]) echo true ;;[span_9](end_span)
        "") echo "$default_value" ;;
        *[span_10](start_span)) echo "$default_value" ;;[span_10](end_span)
    esac
}

# カスタムパッチ設定

read -p "输入内核名称修改(可改中文和emoji，回车默认): " input_suffix
[ -n "$input_suffix" ] && KERNEL_SUFFIX="$input_suffix"

read -p "输入内核构建日期更改(回车默认为原厂): " input_time
[ -n "$input_time" ] && KERNEL_TIME="$input_time"

# KPMはスクリプトの冒頭でfalseに設定済みなので、ここではユーザー入力プロンプトを削除
# ENABLE_KPM=$(prompt_boolean "是否启用KPM？(回车默认开启) [y/N]: " true)
ENABLE_LZ4KD=$(prompt_boolean "是否启用LZ4KD？(回车默认开启) [y/N]: " true)
ENABLE_BBR=$(prompt_boolean "是否启用BBR？(回车默认关闭) [y/N]: " false)

# 選択された機種情報の出力
info "选择的机型: $DEVICE_NAME"
info "内核源码文件: $REPO_MANIFEST"
info "内核名称: $KERNEL_SUFFIX"
info "内核时间: $KERNEL_TIME"
info "是否开启KPM: $ENABLE_KPM"
info "是否开启LZ4KD: $ENABLE_LZ4KD"
info "是否开启BBR: $ENABLE_BBR"

# 環境変数 - 機種別にccacheディレクトリを区別
export CCACHE_COMPILERCHECK="%compiler% -dumpmachine; %compiler% -dumpversion"
export CCACHE_NOHASHDIR="true"
export CCACHE_HARDLINK="true"
export CCACHE_DIR="$HOME/.ccache_${DEVICE_NAME}"  # 機種別に変更
export CCACHE_MAXSIZE="8G"

# ccache初期化フラグファイルも機種別に区別
CCACHE_INIT_FLAG="$CCACHE_DIR/.ccache_initialized"

# ccacheの初期化（初回のみ）
[span_11](start_span)if command -v ccache >/dev/null 2>&1; then[span_11](end_span)
    if [ ! -[span_12](start_span)f "$CCACHE_INIT_FLAG" ]; then[span_12](end_span)
        info "第一次为${DEVICE_NAME}初始化ccache..."
        [span_13](start_span)mkdir -p "$CCACHE_DIR" || error "无法创建ccache目录"[span_13](end_span)
        ccache -M "$CCACHE_MAXSIZE"
        touch "$CCACHE_INIT_FLAG"
    else
        info "ccache (${DEVICE_NAME}) 已初始化，跳过..."
    fi
else
    info "未安装 ccache，跳过初始化"
fi

# 作業ディレクトリ - 機種別に区別
WORKSPACE="$HOME/kernel_${DEVICE_NAME}"
[span_14](start_span)mkdir -p "$WORKSPACE" || error "无法创建工作目录"[span_14](end_span)
cd "$WORKSPACE" || error "无法进入工作目录"

# 依存関係のチェックとインストール
info "检查并安装依赖..."
DEPS=(make python3 git curl ccache flex bison libssl-dev libelf-dev bc zip)
MISSING_DEPS=()

[span_15](start_span)for pkg in "${DEPS[@]}"; do[span_15](end_span)
    [span_16](start_span)if ! dpkg -s "$pkg" >/dev/null 2>&1; then[span_16](end_span)
        MISSING_DEPS+=("$pkg")
    fi
done

[span_17](start_span)if [ ${#MISSING_DEPS[@]} -eq 0 ]; then[span_17](end_span)
    info "所有依赖已安装，跳过安装。"
else
    info "缺少依赖：${MISSING_DEPS[*]}，正在安装..."
    [span_18](start_span)sudo apt update || error "系统更新失败"[span_18](end_span)
    [span_19](start_span)sudo apt install -y "${MISSING_DEPS[@]}" || error "依赖安装失败"[span_19](end_span)
fi

# Gitの設定（未設定の場合のみ）
info "检查 Git 配置..."

GIT_NAME=$(git config --global user.name || echo "")
GIT_EMAIL=$(git config --global user.email || echo "")

if [ -z "$GIT_NAME" ] || [span_20](start_span)[ -z "$GIT_EMAIL" ]; then[span_20](end_span)
    info "Git 未配置，正在设置..."
    git config --global user.name "Q1udaoyu"
    git config --global user.email "sucisama2888@gmail.com"
else
    info "Git 已配置："
fi

# repoツールのインストール（初回のみ）
[span_21](start_span)if ! command -v repo >/dev/null 2>&1; then[span_21](end_span)
    info "安装repo工具..."
    [span_22](start_span)curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo > ~/repo || error "repo下载失败"[span_22](end_span)
    chmod a+x ~/repo
    [span_23](start_span)sudo mv ~/repo /usr/local/bin/repo || error "repo安装失败"[span_23](end_span)
else
    info "repo工具已安装，跳过安装"
fi

# ==================== ソースコード管理 ====================

# ソースコードディレクトリの作成
KERNEL_WORKSPACE="$WORKSPACE/kernel_workspace"

mkdir -p "$KERNEL_WORKSPACE" || error "无法创建kernel_workspace目录"

[span_24](start_span)cd "$KERNEL_WORKSPACE" || error "无法进入kernel_workspace目录"[span_24](end_span)

# ソースコードの初期化
info "初始化repo并同步源码..."
[span_25](start_span)repo init -u https://github.com/showdo/kernel_manifest.git -b refs/heads/oneplus/sm8750 -m "$REPO_MANIFEST" --depth=1 || error "repo初始化失败"[span_25](end_span)
repo --trace sync -c -j$(nproc --all) --no-tags || error "repo同步失败"

# ==================== コアビルド手順 ====================

# クリーンアップ保護エクスポート
info "清理保护导出文件..."
rm -f kernel_platform/common/android/abi_gki_protected_exports_*
rm -f kernel_platform/msm-kernel/android/abi_gki_protected_exports_*

# KernelSU Nextの設定に置換
info "设置KernelSU Next..."
[span_26](start_span)cd kernel_platform || error "进入kernel_platform失败"[span_26](end_span)
# [span_27](start_span)SukiSU-Ultra のセットアップスクリプトを KernelSU Next のダウンロードに置き換え[span_27](end_span)
# 既存の行をコメントアウトまたは削除し、KernelSU Next のリポジトリから最新の KernelSU を設定するコマンドを追加
# rm -rf KernelSU # 既存のKernelSUディレクトリを削除 - KernelSU Nextのsetup.shが処理するため不要
# git clone https://github.com/KernelSU/KernelSU.git # KernelSU Nextのリポジトリをクローン - setup.shが処理するため不要
curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next || error "KernelSU Next設定失敗"

[span_28](start_span)cd KernelSU || error "进入KernelSU目录失败"[span_28](end_span)
KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10700)
export KSU_VERSION=$KSU_VERSION
sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile || error "修改KernelSU版本失败"
info "$KSU_VERSION"

# susfsの設定（KernelSU Nextでは直接含まれるか、別のパッチ適用方法が必要になる場合があります。元のスクリプトのSukiSU関連のsusfsの記述を残しつつ、必要に応じて調整してください。）
info "设置susfs..."
[span_29](start_span)cd "$KERNEL_WORKSPACE" || error "返回工作目录失败"[span_29](end_span)
git clone -q https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android15-6.6 || info "susfs4ksu已存在或克隆失败"
git clone https://github.com/Xiaomichael/kernel_patches.git
# SukiSU_patchのクローンを削除またはコメントアウト
# git clone -q https://github.com/SukiSU-Ultra/SukiSU_patch.git || info "SukiSU_patch已存在或克隆失败"

[span_30](start_span)cd kernel_platform || error "进入kernel_platform失败"[span_30](end_span)
cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch ./common/
cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/

[span_31](start_span)if [ "$ENABLE_LZ4KD" = "true" ]; then[span_31](end_span)
  cp ../kernel_patches/001-lz4.patch ./common/
  cp ../kernel_patches/lz4armv8.S ./common/lib
  cp ../kernel_patches/002-zstd.patch ./common/
fi

cd $KERNEL_WORKSPACE/kernel_platform/common || { echo "进入common目录失败"; exit 1; [span_32](start_span)}


case "$DEVICE_NAME" in
    oneplus_13t|oneplus_ace5_ultra)
        info "当前编译机型为 $DEVICE_NAME, 跳过patch补丁应用"
        ;;[span_32](end_span)
    *)
        info "DEVICE_NAME is $DEVICE_NAME, 正在应用patch补丁..."
        sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-android15-6.6.patch
        sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-android15-6.6.patch
        [span_33](start_span);;[span_33](end_span)
esac

patch -p1 < 50_add_susfs_in_gki-android15-6.6.patch || info "SUSFS补丁应用可能有警告"
# SukiSU_patchからのsyscall_hooks.patchのコピーと適用を削除またはコメントアウト
# [span_34](start_span)cp "$KERNEL_WORKSPACE/SukiSU_patch/hooks/syscall_hooks.patch" ./ || error "复制syscall_hooks.patch失败"[span_34](end_span)
# [span_35](start_span)patch -p1 -F 3 < syscall_hooks.patch || info "syscall_hooks补丁应用可能有警告"[span_35](end_span)
if [ "$ENABLE_LZ4KD" = "true" ]; then
  [span_36](start_span)git apply -p1 < 001-lz4.patch || true[span_36](end_span)
  [span_37](start_span)patch -p1 < 002-zstd.patch || true[span_37](end_span)
fi

# HMBird GKIパッチの適用
apply_hmbird_patch() {
    info "开始应用HMBird GKI补丁..."
    
    # ディレクトリへの移動（エラーチェック付き）
    [span_38](start_span)cd drivers || error "进入drivers目录失败"[span_38](end_span)
    
    # パッチURLの設定（localキーワードを削除）
    patch_url="https://raw.githubusercontent.com/showdo/build_oneplus_sm8750/main/hmbird_patch.c"
    
    info "从GitHub下载补丁文件..."
    [span_39](start_span)if ! curl -sSLo hmbird_patch.c "$patch_url"; then[span_39](end_span)
        error "补丁下载失败，请检查网络或URL: $patch_url"
    fi

    # ファイル内容の検証
    [span_40](start_span)if ! grep -q "MODULE_DESCRIPTION" hmbird_patch.c; then[span_40](end_span)
        error "下载的文件不完整或格式不正确"
    fi

    # Makefileの更新
    info "更新Makefile配置..."
    [span_41](start_span)if ! grep -q "hmbird_patch.o" Makefile; then[span_41](end_span)
        [span_42](start_span)echo "obj-y += hmbird_patch.o" >> Makefile || error "写入Makefile失败"[span_42](end_span)
    fi

    info "HMBird补丁应用成功！"
}

# メインフロー
apply_hmbird_patch

# commonディレクトリに戻る
cd .. || error "返回common目录失败"
[span_43](start_span)cd arch/arm64/configs || error "进入configs目录失败"[span_43](end_span)
# SUSFS設定の追加
info "添加SUSFS配置..."
echo -e "CONFIG_KSU=y
CONFIG_KSU_SUSFS_SUS_SU=n
CONFIG_KSU_MANUAL_HOOK=y
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
CONFIG_KSU_SUSFS_SUS_PATH=n
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_TRY_UMOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=y
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
CONFIG_CRYPTO_LZ4HC=y
CONFIG_CRYPTO_LZ4=y
CONFIG_CRYPTO_LZ4K=y
CONFIG_CRYPTO_842=y
CONFIG_LOCALVERSION_AUTO=n" >> gki_defconfig

# kernel_platformディレクトリに戻る
cd $KERNEL_WORKSPACE/kernel_platform || error "返回kernel_platform目录失败"

# check_defconfigの削除
[span_44](start_span)sudo sed -i 's/check_defconfig//' $KERNEL_WORKSPACE/kernel_platform/common/build.config.gki || error "修改build.config.gki失敗"[span_44](end_span)

# KPM設定はENABLE_KPM=falseなので、このブロックは実行されない
if [ "$ENABLE_KPM" = "true" ]; then
    info "添加KPM配置..."
    echo "CONFIG_KPM=y" >> common/arch/arm64/configs/gki_defconfig
    [span_45](start_span)sudo sed -i 's/check_defconfig//' common/build.config.gki || error "修改build.config.gki失敗"[span_45](end_span)
fi

# BBR設定の追加
if [ "$ENABLE_BBR" = "true" ]; then
    info "添加BBR配置..."
    echo -e "# BBR
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_BBR=y
CONFIG_NET_SCH_FQ=y
CONFIG_TCP_CONG_BIC=n
CONFIG_TCP_CONG_CUBIC=n
CONFIG_TCP_CONG_WESTWOOD=n
CONFIG_TCP_CONG_HTCP=n
CONFIG_DEFAULT_TCP_CONG=bbr" >> common/arch/arm64/configs/gki_defconfig
    [span_46](start_span)sudo sed -i 's/check_defconfig//' common/build.config.gki || error "修改build.config.gki失敗"[span_46](end_span)
fi

# カーネル名の変更
info "修改内核名称..."
sed -i 's/${scm_version}//' common/scripts/setlocalversion || error "修改setlocalversion失敗"
[span_47](start_span)sudo sed -i "s/-4k/${KERNEL_SUFFIX}/g" common/arch/arm64/configs/gki_defconfig || error "修改gki_defconfig失敗"[span_47](end_span)

# 完美風馳パッチの適用
info "应用完美风驰补丁..."
cd $KERNEL_WORKSPACE/kernel_platform/
git clone https://github.com/HanKuCha/sched_ext.git
cp -r ./sched_ext/* ./common/kernel/sched
rm -rf ./sched_ext/.git
[span_48](start_span)cd $KERNEL_WORKSPACE/kernel_platform/common/kernel/sched  || error "跳转sched目录失敗"[span_48](end_span)

# カーネルのビルド
info "开始构建内核..."
export KBUILD_BUILD_TIMESTAMP="$KERNEL_TIME"
export PATH="$KERNEL_WORKSPACE/kernel_platform/prebuilts/clang/host/linux-x86/clang-r510928/bin:$PATH"
export PATH="/usr/lib/ccache:$PATH"

cd $KERNEL_WORKSPACE/kernel_platform/common || error "进入common目录失敗"

# .configの生成
make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang \
  RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc \
  PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole \
  [span_49](start_span)LD=ld.lld HOSTLD=ld.lld O=out KCFLAGS+=-O2 gki_defconfig all || error "失敗"[span_49](end_span)


# Linuxパッチの適用
info "应用Linux补丁..."
[span_50](start_span)cd out/arch/arm64/boot || error "进入boot目录失敗"[span_50](end_span)
# SukiSU_KernelPatch_patchからのpatch_linuxのダウンロードと適用をKernelSUの対応するパッチに置き換えるか、元のスクリプトでKernelSUがすでにこれを処理している場合は削除
# [span_51](start_span)curl -LO https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.12.0/patch_linux || error "下载patch_linux失敗"[span_51](end_span)
# chmod +x patch_linux
# [span_52](start_span)./patch_linux || error "应用patch_linux失敗"[span_52](end_span)
rm -f Image
mv oImage Image || error "替换Image失敗"

# AnyKernel3パッケージの作成
info "创建AnyKernel3包..."
cd "$WORKSPACE" || error "返回工作目录失敗"
[span_53](start_span)git clone -q https://github.com/showdo/AnyKernel3.git --depth=1 || info "AnyKernel3已存在"[span_53](end_span)
rm -rf ./AnyKernel3/.git
rm -f ./AnyKernel3/push.sh
cp "$KERNEL_WORKSPACE/kernel_platform/common/out/arch/arm64/boot/Image" ./AnyKernel3/ || error "复制Image失敗"

# パッケージング
cd AnyKernel3 || error "进入AnyKernel3目录失敗"
# パッケージ名にSukiSUの代わりにKernelSUを含めるように変更
[span_54](start_span)zip -r "AnyKernel3_${KSU_VERSION}_${DEVICE_NAME}_KernelSU.zip" ./* || error "打包失敗"[span_54](end_span)

# Cドライブ出力ディレクトリの作成（WSL経由でWindowsのCドライブにアクセス）
WIN_OUTPUT_DIR="/mnt/c/Kernel_Build/${DEVICE_NAME}/"
mkdir -p "$WIN_OUTPUT_DIR" || error "无法创建Windows目录，可能未挂载C盘，将保存到Linux目录:$WORKSPACE/AnyKernel3/AnyKernel3_${KSU_VERSION}_${DEVICE_NAME}_KernelSU.zip"

# ImageとAnyKernel3パッケージのコピー
cp "$KERNEL_WORKSPACE/kernel_platform/common/out/arch/arm64/boot/Image" "$WIN_OUTPUT_DIR/"
cp "$WORKSPACE/AnyKernel3/AnyKernel3_${KSU_VERSION}_${DEVICE_NAME}_KernelSU.zip" "$WIN_OUTPUT_DIR/"

rm -rf $WORKSPACE
info "内核包路径: C:/Kernel_Build/${DEVICE_NAME}/AnyKernel3_${KSU_VERSION}_${DEVICE_NAME}_KernelSU.zip"
info "Image路径: C:/Kernel_Build/${DEVICE_NAME}/Image"
info "请在C盘目录中查找内核包和Image文件。"
